// This file is auto-generated by @hey-api/openapi-ts

export const AskAIRequestSchema = {
    properties: {
        question: {
            type: 'string',
            title: 'Question'
        }
    },
    type: 'object',
    required: ['question'],
    title: 'AskAIRequest'
} as const;

export const BankEntrySchema = {
    properties: {
        amount: {
            type: 'number',
            title: 'Amount'
        },
        date: {
            type: 'string',
            title: 'Date'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        payer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payer'
        }
    },
    type: 'object',
    required: ['amount', 'date'],
    title: 'BankEntry'
} as const;

export const BankStatementPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            title: 'Organization Id'
        },
        uploaded_by: {
            type: 'string',
            format: 'uuid',
            title: 'Uploaded By'
        },
        original_filename: {
            type: 'string',
            title: 'Original Filename'
        },
        uploaded_at: {
            type: 'string',
            format: 'date-time',
            title: 'Uploaded At'
        },
        parsed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parsed At'
        },
        statement_month: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Statement Month'
        },
        bank_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bank Name'
        },
        account_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Account Number'
        }
    },
    type: 'object',
    required: ['id', 'organization_id', 'uploaded_by', 'original_filename', 'uploaded_at', 'parsed_at', 'statement_month', 'bank_name', 'account_number'],
    title: 'BankStatementPublic'
} as const;

export const BankTransactionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        statement_id: {
            type: 'string',
            format: 'uuid',
            title: 'Statement Id'
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            title: 'Organization Id'
        },
        date: {
            type: 'string',
            title: 'Date'
        },
        amount: {
            type: 'number',
            title: 'Amount'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        reference: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reference'
        },
        matched_document_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Matched Document Id'
        },
        confidence_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Confidence Score'
        },
        status: {
            type: 'string',
            title: 'Status'
        }
    },
    type: 'object',
    required: ['id', 'statement_id', 'organization_id', 'date', 'amount', 'currency', 'description', 'reference', 'matched_document_id', 'confidence_score', 'status'],
    title: 'BankTransactionPublic'
} as const;

export const BankTransactionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BankTransactionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BankTransactionsPublic'
} as const;

export const Body_files_upload_fileSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_files-upload_file'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_statements_upload_bank_statementSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_statements-upload_bank_statement'
} as const;

export const ChatRequestSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        history: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'History',
            default: []
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ChatRequest'
} as const;

export const ChatResponseSchema = {
    properties: {
        reply: {
            type: 'string',
            title: 'Reply'
        }
    },
    type: 'object',
    required: ['reply'],
    title: 'ChatResponse'
} as const;

export const CorrectionRequestSchema = {
    properties: {
        document_id: {
            type: 'string',
            format: 'uuid',
            title: 'Document Id'
        },
        user_decision: {
            type: 'string',
            title: 'User Decision'
        },
        user_matched_index: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Matched Index'
        },
        user_note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Note'
        }
    },
    type: 'object',
    required: ['document_id', 'user_decision'],
    title: 'CorrectionRequest',
    description: 'Request to record a user correction for AI learning.'
} as const;

export const CorrectionResponseSchema = {
    properties: {
        correction_id: {
            type: 'string',
            format: 'uuid',
            title: 'Correction Id'
        },
        learned_patterns: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Learned Patterns'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['correction_id', 'learned_patterns', 'message'],
    title: 'CorrectionResponse',
    description: 'Response after recording a correction.'
} as const;

export const DocumentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            title: 'Organization Id'
        },
        original_filename: {
            type: 'string',
            title: 'Original Filename'
        },
        s3_key: {
            type: 'string',
            title: 'S3 Key'
        },
        file_type: {
            type: 'string',
            title: 'File Type'
        },
        uploaded_at: {
            type: 'string',
            format: 'date-time',
            title: 'Uploaded At'
        },
        extracted_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extracted Data'
        },
        reconciliation_result: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reconciliation Result'
        },
        original_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Original Amount'
        },
        original_currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Original Currency'
        },
        transaction_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Transaction Date'
        },
        base_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Amount'
        },
        base_currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Currency',
            default: 'MYR'
        },
        fx_rate_used: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fx Rate Used'
        },
        fx_rate_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fx Rate Date'
        },
        fx_rate_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fx Rate Timestamp'
        },
        ai_result: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Result'
        },
        ai_confidence: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Confidence'
        },
        ai_explanation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Explanation'
        },
        workflow_status: {
            type: 'string',
            title: 'Workflow Status',
            default: 'PENDING_EXTRACTION'
        },
        review_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Review Status'
        },
        review_note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Review Note'
        },
        reviewed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewed At'
        },
        reviewed_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewed By'
        },
        exception_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Exception Type'
        },
        case_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Case Id'
        },
        risk_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Score'
        },
        risk_level: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Level'
        }
    },
    type: 'object',
    required: ['id', 'organization_id', 'original_filename', 's3_key', 'file_type', 'uploaded_at'],
    title: 'DocumentPublic'
} as const;

export const DocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DocumentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DocumentsPublic'
} as const;

export const ExtractedDataSchema = {
    properties: {
        amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount'
        },
        currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date'
        },
        payer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payer'
        },
        payee: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payee'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        myr_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Myr Amount'
        },
        fx_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fx Rate'
        }
    },
    type: 'object',
    title: 'ExtractedData'
} as const;

export const ExtractionResponseSchema = {
    properties: {
        document_id: {
            type: 'string',
            format: 'uuid',
            title: 'Document Id'
        },
        extracted: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ExtractedData'
                },
                {
                    type: 'null'
                }
            ]
        },
        rows: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ExtractedData'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rows'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['document_id'],
    title: 'ExtractionResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InvitationAcceptSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['token', 'password'],
    title: 'InvitationAccept'
} as const;

export const InvitationCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        role: {
            type: 'string',
            title: 'Role',
            default: 'VIEWER'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'InvitationCreate'
} as const;

export const InvitationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            title: 'Organization Id'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        invited_by: {
            type: 'string',
            format: 'uuid',
            title: 'Invited By'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        },
        accepted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Accepted At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'email', 'organization_id', 'role', 'invited_by', 'expires_at', 'accepted_at', 'created_at'],
    title: 'InvitationPublic'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LearningInsightsResponseSchema = {
    properties: {
        vendor_preferences: {
            items: {
                '$ref': '#/components/schemas/VendorPreferencePublic'
            },
            type: 'array',
            title: 'Vendor Preferences'
        },
        reconciliation_patterns: {
            items: {
                '$ref': '#/components/schemas/ReconciliationPatternPublic'
            },
            type: 'array',
            title: 'Reconciliation Patterns'
        },
        total_corrections: {
            type: 'integer',
            title: 'Total Corrections'
        }
    },
    type: 'object',
    required: ['vendor_preferences', 'reconciliation_patterns', 'total_corrections'],
    title: 'LearningInsightsResponse',
    description: 'Learning insights for an organization.'
} as const;

export const MemberWithUserSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            title: 'Organization Id'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        joined_at: {
            type: 'string',
            format: 'date-time',
            title: 'Joined At'
        },
        user_email: {
            type: 'string',
            title: 'User Email'
        },
        user_full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Full Name'
        },
        user_is_active: {
            type: 'boolean',
            title: 'User Is Active'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'organization_id', 'role', 'joined_at', 'user_email', 'user_full_name', 'user_is_active'],
    title: 'MemberWithUser'
} as const;

export const MembersWithUsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MemberWithUser'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MembersWithUsersPublic'
} as const;

export const MembershipCreateSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            title: 'Organization Id'
        },
        role: {
            type: 'string',
            title: 'Role',
            default: 'VIEWER'
        }
    },
    type: 'object',
    required: ['user_id', 'organization_id'],
    title: 'MembershipCreate'
} as const;

export const MembershipPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            title: 'Organization Id'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        joined_at: {
            type: 'string',
            format: 'date-time',
            title: 'Joined At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'organization_id', 'role', 'joined_at'],
    title: 'MembershipPublic'
} as const;

export const MembershipUpdateSchema = {
    properties: {
        role: {
            type: 'string',
            title: 'Role'
        }
    },
    type: 'object',
    required: ['role'],
    title: 'MembershipUpdate'
} as const;

export const MembershipsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MembershipPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MembershipsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OrganizationCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        base_currency: {
            type: 'string',
            maxLength: 3,
            title: 'Base Currency',
            default: 'MYR'
        },
        timezone: {
            type: 'string',
            maxLength: 100,
            title: 'Timezone',
            default: 'Asia/Kuala_Lumpur'
        },
        fx_provider: {
            type: 'string',
            maxLength: 50,
            title: 'Fx Provider',
            default: 'frankfurter'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'OrganizationCreate'
} as const;

export const OrganizationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        base_currency: {
            type: 'string',
            title: 'Base Currency'
        },
        timezone: {
            type: 'string',
            title: 'Timezone'
        },
        fx_provider: {
            type: 'string',
            title: 'Fx Provider'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'base_currency', 'timezone', 'fx_provider', 'created_at'],
    title: 'OrganizationPublic'
} as const;

export const OrganizationUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        base_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Currency'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone'
        },
        fx_provider: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fx Provider'
        }
    },
    type: 'object',
    title: 'OrganizationUpdate'
} as const;

export const OrganizationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OrganizationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'OrganizationsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ReconcileRequestSchema = {
    properties: {
        document_id: {
            type: 'string',
            format: 'uuid',
            title: 'Document Id'
        },
        bank_entries: {
            items: {
                '$ref': '#/components/schemas/BankEntry'
            },
            type: 'array',
            title: 'Bank Entries'
        },
        override_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Override Date'
        }
    },
    type: 'object',
    required: ['document_id', 'bank_entries'],
    title: 'ReconcileRequest'
} as const;

export const ReconcileResponseSchema = {
    properties: {
        document_id: {
            type: 'string',
            format: 'uuid',
            title: 'Document Id'
        },
        result: {
            additionalProperties: true,
            type: 'object',
            title: 'Result'
        }
    },
    type: 'object',
    required: ['document_id', 'result'],
    title: 'ReconcileResponse'
} as const;

export const ReconciliationPatternPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        pattern_type: {
            type: 'string',
            title: 'Pattern Type'
        },
        pattern_name: {
            type: 'string',
            title: 'Pattern Name'
        },
        pattern_rule: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pattern Rule'
        },
        learned_from_count: {
            type: 'integer',
            title: 'Learned From Count'
        },
        success_rate: {
            type: 'number',
            title: 'Success Rate'
        }
    },
    type: 'object',
    required: ['id', 'pattern_type', 'pattern_name', 'pattern_rule', 'learned_from_count', 'success_rate'],
    title: 'ReconciliationPatternPublic',
    description: 'Public representation of a learned reconciliation pattern.'
} as const;

export const ReconciliationRecordPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        document_id: {
            type: 'string',
            format: 'uuid',
            title: 'Document Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        reviewed_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewed By'
        },
        confidence: {
            type: 'number',
            title: 'Confidence'
        },
        risk_score: {
            type: 'integer',
            title: 'Risk Score'
        },
        risk_level: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Level'
        },
        fx_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fx Rate'
        },
        normalized_amount_myr: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Normalized Amount Myr'
        },
        base_currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Currency'
        },
        base_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Amount'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        exception_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Exception Type'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        ai_explanation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Explanation'
        },
        case_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Case Id'
        },
        assigned_to: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assigned To'
        },
        priority: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        },
        risk_factors: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Risk Factors'
        },
        journal_entry: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Journal Entry'
        }
    },
    type: 'object',
    required: ['id', 'document_id', 'created_at', 'reviewed_by', 'confidence', 'risk_score', 'risk_level', 'fx_rate', 'normalized_amount_myr', 'base_currency', 'base_amount', 'action', 'exception_type', 'note', 'ai_explanation', 'case_id', 'assigned_to', 'priority', 'risk_factors', 'journal_entry'],
    title: 'ReconciliationRecordPublic'
} as const;

export const ReviewActionRequestSchema = {
    properties: {
        action: {
            type: 'string',
            title: 'Action'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        exception_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Exception Type'
        },
        priority: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        }
    },
    type: 'object',
    required: ['action'],
    title: 'ReviewActionRequest'
} as const;

export const SuggestMatchesResponseSchema = {
    properties: {
        document_id: {
            type: 'string',
            format: 'uuid',
            title: 'Document Id'
        },
        extracted_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Extracted Data'
        },
        suggested_matches: {
            items: {
                '$ref': '#/components/schemas/SuggestedMatch'
            },
            type: 'array',
            title: 'Suggested Matches'
        }
    },
    type: 'object',
    required: ['document_id', 'extracted_data', 'suggested_matches'],
    title: 'SuggestMatchesResponse'
} as const;

export const SuggestedMatchSchema = {
    properties: {
        transaction: {
            '$ref': '#/components/schemas/BankTransactionPublic'
        },
        confidence: {
            type: 'number',
            title: 'Confidence'
        },
        explanation: {
            type: 'string',
            title: 'Explanation'
        }
    },
    type: 'object',
    required: ['transaction', 'confidence', 'explanation'],
    title: 'SuggestedMatch',
    description: 'A suggested bank transaction match for a document'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UploadResponseSchema = {
    properties: {
        document: {
            '$ref': '#/components/schemas/DocumentPublic'
        }
    },
    type: 'object',
    required: ['document'],
    title: 'UploadResponse'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        organization_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Organization Id'
        },
        display_currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Currency',
            default: 'MYR'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VendorPreferencePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        canonical_vendor_name: {
            type: 'string',
            title: 'Canonical Vendor Name'
        },
        vendor_aliases: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vendor Aliases'
        },
        typical_amount_range: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Typical Amount Range'
        },
        is_recurring: {
            type: 'boolean',
            title: 'Is Recurring'
        },
        learned_from_count: {
            type: 'integer',
            title: 'Learned From Count'
        },
        confidence: {
            type: 'number',
            title: 'Confidence'
        }
    },
    type: 'object',
    required: ['id', 'canonical_vendor_name', 'vendor_aliases', 'typical_amount_range', 'is_recurring', 'learned_from_count', 'confidence'],
    title: 'VendorPreferencePublic',
    description: 'Public representation of a learned vendor preference.'
} as const;