// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ChatChatData, ChatChatResponse, FilesGeneratePresignedUrlData, FilesGeneratePresignedUrlResponse, FilesUploadFileData, FilesUploadFileResponse, FilesListMyDocumentsData, FilesListMyDocumentsResponse, FilesDeleteFileData, FilesDeleteFileResponse, FilesGetDownloadUrlData, FilesGetDownloadUrlResponse, FilesExtractDocumentData, FilesExtractDocumentResponse, FxCurrenciesResponse, FxCurrencyRateData, FxCurrencyRateResponse, FxConvertCurrencyData, FxConvertCurrencyResponse, FxConvertToMyrEndpointData, FxConvertToMyrEndpointResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, ReconciliationReconcileDocumentData, ReconciliationReconcileDocumentResponse, ReviewReviewDocumentData, ReviewReviewDocumentResponse, ReviewGetAuditTrailData, ReviewGetAuditTrailResponse, ReviewAskAiQuestionData, ReviewAskAiQuestionResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class ChatService {
    /**
     * Chat
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ChatResponse Successful Response
     * @throws ApiError
     */
    public static chat(data: ChatChatData): CancelablePromise<ChatChatResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/chat/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class FilesService {
    /**
     * Generate Presigned Url
     * @param data The data for the request.
     * @param data.filename
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static generatePresignedUrl(data: FilesGeneratePresignedUrlData): CancelablePromise<FilesGeneratePresignedUrlResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/files/presigned-url',
            query: {
                filename: data.filename
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Upload File
     * @param data The data for the request.
     * @param data.formData
     * @returns UploadResponse Successful Response
     * @throws ApiError
     */
    public static uploadFile(data: FilesUploadFileData): CancelablePromise<FilesUploadFileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/files/upload',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List My Documents
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns DocumentsPublic Successful Response
     * @throws ApiError
     */
    public static listMyDocuments(data: FilesListMyDocumentsData = {}): CancelablePromise<FilesListMyDocumentsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/files/my-documents',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete File
     * @param data The data for the request.
     * @param data.documentId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteFile(data: FilesDeleteFileData): CancelablePromise<FilesDeleteFileResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/files/{document_id}',
            path: {
                document_id: data.documentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Download Url
     * @param data The data for the request.
     * @param data.documentId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getDownloadUrl(data: FilesGetDownloadUrlData): CancelablePromise<FilesGetDownloadUrlResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/files/{document_id}/download-url',
            path: {
                document_id: data.documentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Extract Document
     * @param data The data for the request.
     * @param data.documentId
     * @returns ExtractionResponse Successful Response
     * @throws ApiError
     */
    public static extractDocument(data: FilesExtractDocumentData): CancelablePromise<FilesExtractDocumentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/files/{document_id}/extract',
            path: {
                document_id: data.documentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class FxService {
    /**
     * Currencies
     * List all supported currencies.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static currencies(): CancelablePromise<FxCurrenciesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fx/currencies'
        });
    }
    
    /**
     * Currency Rate
     * Get rate between two currencies. Supports historical dates back to 1948.
     * @param data The data for the request.
     * @param data.fromCurrency
     * @param data.toCurrency
     * @param data.onDate YYYY-MM-DD or 'latest'
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static currencyRate(data: FxCurrencyRateData): CancelablePromise<FxCurrencyRateResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fx/rate/{from_currency}/{to_currency}',
            path: {
                from_currency: data.fromCurrency,
                to_currency: data.toCurrency
            },
            query: {
                on_date: data.onDate
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Convert Currency
     * Convert amount between currencies on a specific date.
     * @param data The data for the request.
     * @param data.amount
     * @param data.fromCurrency
     * @param data.toCurrency
     * @param data.onDate YYYY-MM-DD or 'latest'
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static convertCurrency(data: FxConvertCurrencyData): CancelablePromise<FxConvertCurrencyResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fx/convert',
            query: {
                amount: data.amount,
                from_currency: data.fromCurrency,
                to_currency: data.toCurrency,
                on_date: data.onDate
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Convert To Myr Endpoint
     * Convert any currency to MYR using the rate on the transaction date.
     * @param data The data for the request.
     * @param data.amount
     * @param data.fromCurrency
     * @param data.onDate YYYY-MM-DD or 'latest'
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static convertToMyrEndpoint(data: FxConvertToMyrEndpointData): CancelablePromise<FxConvertToMyrEndpointResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/fx/convert-to-myr',
            query: {
                amount: data.amount,
                from_currency: data.fromCurrency,
                on_date: data.onDate
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ReconciliationService {
    /**
     * Reconcile Document
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ReconcileResponse Successful Response
     * @throws ApiError
     */
    public static reconcileDocument(data: ReconciliationReconcileDocumentData): CancelablePromise<ReconciliationReconcileDocumentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reconciliation/reconcile',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ReviewService {
    /**
     * Review Document
     * @param data The data for the request.
     * @param data.documentId
     * @param data.requestBody
     * @returns ReconciliationRecordPublic Successful Response
     * @throws ApiError
     */
    public static reviewDocument(data: ReviewReviewDocumentData): CancelablePromise<ReviewReviewDocumentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/files/{document_id}/review',
            path: {
                document_id: data.documentId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Audit Trail
     * Return all review records for a document — full audit trail.
     * @param data The data for the request.
     * @param data.documentId
     * @returns ReconciliationRecordPublic Successful Response
     * @throws ApiError
     */
    public static getAuditTrail(data: ReviewGetAuditTrailData): CancelablePromise<ReviewGetAuditTrailResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/files/{document_id}/audit-trail',
            path: {
                document_id: data.documentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Ask Ai Question
     * @param data The data for the request.
     * @param data.documentId
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static askAiQuestion(data: ReviewAskAiQuestionData): CancelablePromise<ReviewAskAiQuestionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/files/{document_id}/ask-ai',
            path: {
                document_id: data.documentId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}