// This file is auto-generated by @hey-api/openapi-ts

export type BankEntry = {
    amount: number;
    date: string;
    description?: (string | null);
    payer?: (string | null);
};

export type Body_files_upload_file = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatRequest = {
    message: string;
    history?: Array<{
        [key: string]: unknown;
    }>;
};

export type ChatResponse = {
    reply: string;
};

export type DocumentPublic = {
    id: string;
    original_filename: string;
    s3_key: string;
    file_type: string;
    uploaded_at: string;
    extracted_data?: ({
    [key: string]: unknown;
} | null);
    reconciliation_result?: ({
    [key: string]: unknown;
} | null);
    review_status?: (string | null);
    review_note?: (string | null);
    reviewed_at?: (string | null);
};

export type DocumentsPublic = {
    data: Array<DocumentPublic>;
    count: number;
};

export type ExtractedData = {
    amount?: (number | null);
    currency?: (string | null);
    date?: (string | null);
    payer?: (string | null);
    payee?: (string | null);
    description?: (string | null);
    myr_amount?: (number | null);
    fx_rate?: (number | null);
};

export type ExtractionResponse = {
    document_id: string;
    extracted?: (ExtractedData | null);
    rows?: (Array<ExtractedData> | null);
    error?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReconcileRequest = {
    document_id: string;
    bank_entries: Array<BankEntry>;
    override_date?: (string | null);
};

export type ReconcileResponse = {
    document_id: string;
    result: {
        [key: string]: unknown;
    };
};

export type ReviewRequest = {
    status: string;
    note?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UploadResponse = {
    document: DocumentPublic;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ChatChatData = {
    requestBody: ChatRequest;
};

export type ChatChatResponse = (ChatResponse);

export type FilesGeneratePresignedUrlData = {
    filename: string;
};

export type FilesGeneratePresignedUrlResponse = (unknown);

export type FilesUploadFileData = {
    formData: Body_files_upload_file;
};

export type FilesUploadFileResponse = (UploadResponse);

export type FilesListMyDocumentsData = {
    limit?: number;
    skip?: number;
};

export type FilesListMyDocumentsResponse = (DocumentsPublic);

export type FilesDeleteFileData = {
    documentId: string;
};

export type FilesDeleteFileResponse = (unknown);

export type FilesGetDownloadUrlData = {
    documentId: string;
};

export type FilesGetDownloadUrlResponse = (unknown);

export type FilesExtractDocumentData = {
    documentId: string;
};

export type FilesExtractDocumentResponse = (ExtractionResponse);

export type FilesReviewDocumentData = {
    documentId: string;
    requestBody: ReviewRequest;
};

export type FilesReviewDocumentResponse = (unknown);

export type FxCurrenciesResponse = (unknown);

export type FxCurrencyRateData = {
    fromCurrency: string;
    /**
     * YYYY-MM-DD or 'latest'
     */
    onDate?: string;
    toCurrency: string;
};

export type FxCurrencyRateResponse = (unknown);

export type FxConvertCurrencyData = {
    amount: number;
    fromCurrency: string;
    /**
     * YYYY-MM-DD or 'latest'
     */
    onDate?: string;
    toCurrency: string;
};

export type FxConvertCurrencyResponse = (unknown);

export type FxConvertToMyrEndpointData = {
    amount: number;
    fromCurrency: string;
    /**
     * YYYY-MM-DD or 'latest'
     */
    onDate?: string;
};

export type FxConvertToMyrEndpointResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ReconciliationReconcileDocumentData = {
    requestBody: ReconcileRequest;
};

export type ReconciliationReconcileDocumentResponse = (ReconcileResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);