"""
PDF Report Generator for Reconciliation Results

Generates comprehensive PDF reports with AI reasoning, risk assessment,
and visual summaries of reconciliation outcomes.
"""

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    Image,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY


def generate_reconciliation_report(
    results: list[dict[str, Any]],
    organization_name: str,
    generated_by: str,
    include_summary: bool = True,
    include_details: bool = True,
) -> bytes:
    """
    Generate a comprehensive PDF report for reconciliation results.

    Args:
        results: List of reconciliation results
        organization_name: Name of the organization
        generated_by: User who generated the report
        include_summary: Include executive summary
        include_details: Include detailed breakdown per document

    Returns:
        PDF file as bytes
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72,
    )

    # Container for the 'Flowable' objects
    elements = []

    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=24,
        textColor=colors.HexColor("#1e40af"),
        spaceAfter=30,
        alignment=TA_CENTER,
    )
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=16,
        textColor=colors.HexColor("#1e40af"),
        spaceAfter=12,
        spaceBefore=12,
    )
    subheading_style = ParagraphStyle(
        "CustomSubHeading",
        parent=styles["Heading3"],
        fontSize=13,
        textColor=colors.HexColor("#374151"),
        spaceAfter=8,
        spaceBefore=8,
    )
    normal_style = styles["Normal"]
    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["BodyText"],
        fontSize=10,
        alignment=TA_JUSTIFY,
    )

    # Title Page
    elements.append(Paragraph("Reconciliation Report", title_style))
    elements.append(Spacer(1, 0.2 * inch))

    # Report metadata
    metadata = [
        ["Organization:", organization_name],
        ["Generated By:", generated_by],
        ["Generated Date:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["Documents Processed:", str(len(results))],
    ]

    metadata_table = Table(metadata, colWidths=[2 * inch, 4 * inch])
    metadata_table.setStyle(
        TableStyle(
            [
                ("ALIGN", (0, 0), (0, -1), "RIGHT"),
                ("ALIGN", (1, 0), (1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    elements.append(metadata_table)
    elements.append(Spacer(1, 0.5 * inch))

    # Executive Summary
    if include_summary:
        elements.append(Paragraph("Executive Summary", heading_style))
        elements.append(Spacer(1, 0.1 * inch))

        # Calculate statistics
        total_docs = len(results)
        matched = sum(
            1
            for r in results
            if r.get("result", {})
            .get("agent_decision", {})
            .get("final_status")
            in ["matched", "matched_with_adjustment"]
        )
        fuzzy = sum(
            1
            for r in results
            if r.get("result", {}).get("agent_decision", {}).get("final_status")
            == "fuzzy"
        )
        unmatched = sum(
            1
            for r in results
            if r.get("result", {}).get("agent_decision", {}).get("final_status")
            == "unmatched"
        )
        errors = sum(1 for r in results if r.get("error"))

        avg_confidence = (
            sum(
                r.get("result", {}).get("agent_decision", {}).get("confidence", 0)
                for r in results
                if not r.get("error")
            )
            / max(total_docs - errors, 1)
            * 100
        )

        # Summary statistics table
        summary_data = [
            ["Metric", "Count", "Percentage"],
            [
                "Total Documents",
                str(total_docs),
                "100%",
            ],
            [
                "✓ Matched",
                str(matched),
                f"{(matched / total_docs * 100):.1f}%",
            ],
            [
                "~ Fuzzy Match",
                str(fuzzy),
                f"{(fuzzy / total_docs * 100):.1f}%",
            ],
            [
                "✗ Unmatched",
                str(unmatched),
                f"{(unmatched / total_docs * 100):.1f}%",
            ],
            [
                "⚠ Errors",
                str(errors),
                f"{(errors / total_docs * 100):.1f}%",
            ],
            [
                "Average AI Confidence",
                f"{avg_confidence:.1f}%",
                "-",
            ],
        ]

        summary_table = Table(summary_data, colWidths=[2.5 * inch, 1.5 * inch, 1.5 * inch])
        summary_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 11),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("FONTSIZE", (0, 1), (-1, -1), 10),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
                ]
            )
        )
        elements.append(summary_table)
        elements.append(Spacer(1, 0.3 * inch))

        # Key insights
        elements.append(Paragraph("Key Insights", subheading_style))

        insights = []
        if matched / total_docs > 0.8:
            insights.append(
                f"• <b>High Success Rate:</b> {(matched / total_docs * 100):.1f}% of documents were successfully matched with high confidence."
            )
        elif matched / total_docs < 0.5:
            insights.append(
                f"• <b>Low Match Rate:</b> Only {(matched / total_docs * 100):.1f}% matched. Review bank statement data quality and date ranges."
            )

        if avg_confidence > 85:
            insights.append(
                f"• <b>High AI Confidence:</b> Average confidence of {avg_confidence:.1f}% indicates reliable automated decisions."
            )
        elif avg_confidence < 70:
            insights.append(
                f"• <b>Moderate Confidence:</b> Average confidence of {avg_confidence:.1f}% suggests manual review recommended."
            )

        if fuzzy > 0:
            insights.append(
                f"• <b>Fuzzy Matches:</b> {fuzzy} documents require human review for final approval."
            )

        # Count adjustments
        adjustments = sum(
            1
            for r in results
            if r.get("result", {})
            .get("agent_decision", {})
            .get("adjustment_type")
            is not None
        )
        if adjustments > 0:
            insights.append(
                f"• <b>Adjustments Proposed:</b> {adjustments} transactions have AI-proposed journal entry adjustments (bank fees, FX spreads, etc.)."
            )

        for insight in insights:
            elements.append(Paragraph(insight, body_style))
            elements.append(Spacer(1, 0.05 * inch))

        elements.append(PageBreak())

    # Detailed Results
    if include_details:
        elements.append(Paragraph("Detailed Reconciliation Results", heading_style))
        elements.append(Spacer(1, 0.2 * inch))

        for idx, result in enumerate(results, 1):
            doc_name = result.get("docName", f"Document {idx}")
            error = result.get("error")

            # Document header
            elements.append(
                Paragraph(f"<b>Document {idx}: {doc_name}</b>", subheading_style)
            )

            if error:
                # Error case
                error_para = Paragraph(
                    f'<font color="red"><b>Error:</b> {error}</font>',
                    normal_style,
                )
                elements.append(error_para)
                elements.append(Spacer(1, 0.2 * inch))
                continue

            # Extract data
            agent_decision = result.get("result", {}).get("agent_decision", {})
            proof = result.get("result", {}).get("proof", {})
            fx_result = result.get("result", {}).get("fx_result")

            status = agent_decision.get("final_status", "unknown")
            confidence = agent_decision.get("confidence", 0)
            explanation = agent_decision.get("explanation", "No explanation provided")
            matched_idx = agent_decision.get("matched_entry_index")
            adjustment_type = agent_decision.get("adjustment_type")
            adjustment_amount = agent_decision.get("adjustment_amount", 0)

            # Status badge
            status_colors = {
                "matched": colors.green,
                "matched_with_adjustment": colors.green,
                "fuzzy": colors.orange,
                "unmatched": colors.red,
            }
            status_color = status_colors.get(status, colors.grey)

            status_labels = {
                "matched": "✓ MATCHED",
                "matched_with_adjustment": "✓ MATCHED (with adjustment)",
                "fuzzy": "~ FUZZY MATCH",
                "unmatched": "✗ UNMATCHED",
            }
            status_label = status_labels.get(status, status.upper())

            elements.append(
                Paragraph(
                    f'<font color="{status_color.hexval()}"><b>{status_label}</b></font> | '
                    f'Confidence: <b>{confidence * 100:.1f}%</b>',
                    normal_style,
                )
            )
            elements.append(Spacer(1, 0.1 * inch))

            # Transaction details
            details_data = [
                ["Field", "Value"],
                ["Amount", f"{proof.get('currency', 'N/A')} {proof.get('amount', 'N/A')}"],
                ["Date", proof.get("date", "N/A")],
                ["Payer", proof.get("payer", "N/A")],
                ["Payee", proof.get("payee", "N/A")],
            ]

            if fx_result:
                details_data.append(
                    [
                        "Converted Amount",
                        f"{fx_result.get('to_currency', 'N/A')} {fx_result.get('to_amount', 'N/A')} (rate: {fx_result.get('rate', 'N/A')})",
                    ]
                )

            if matched_idx is not None:
                bank_entries = result.get("result", {}).get("bank_entries", [])
                if matched_idx < len(bank_entries):
                    matched_entry = bank_entries[matched_idx]
                    details_data.append(
                        [
                            "Matched Bank Entry",
                            f"{matched_entry.get('date', 'N/A')}: {matched_entry.get('description', 'N/A')}",
                        ]
                    )

            if adjustment_type:
                details_data.append(
                    [
                        "Adjustment Type",
                        adjustment_type.replace("_", " ").title(),
                    ]
                )
                details_data.append(
                    [
                        "Adjustment Amount",
                        f"{fx_result.get('to_currency', 'MYR') if fx_result else 'MYR'} {adjustment_amount:.2f}",
                    ]
                )

            details_table = Table(details_data, colWidths=[2 * inch, 4 * inch])
            details_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, -1), 9),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 6),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ]
                )
            )
            elements.append(details_table)
            elements.append(Spacer(1, 0.15 * inch))

            # AI Reasoning
            elements.append(Paragraph("<b>AI Reasoning:</b>", normal_style))
            elements.append(Spacer(1, 0.05 * inch))

            reasoning_para = Paragraph(explanation, body_style)
            elements.append(reasoning_para)

            # Journal entry proposal (if applicable)
            journal_entry = agent_decision.get("journal_entry_proposal")
            if journal_entry:
                elements.append(Spacer(1, 0.1 * inch))
                elements.append(Paragraph("<b>Proposed Journal Entry:</b>", normal_style))
                elements.append(Spacer(1, 0.05 * inch))

                journal_data = [
                    ["Account", "Debit", "Credit"],
                    [
                        journal_entry.get("debit_account", ""),
                        f"{journal_entry.get('debit_amount', 0):.2f}",
                        "-",
                    ],
                    [
                        journal_entry.get("credit_account", ""),
                        "-",
                        f"{journal_entry.get('credit_amount', 0):.2f}",
                    ],
                ]

                journal_table = Table(journal_data, colWidths=[3 * inch, 1.5 * inch, 1.5 * inch])
                journal_table.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#dbeafe")),
                            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                            ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
                            ("FONTSIZE", (0, 0), (-1, -1), 9),
                            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
                        ]
                    )
                )
                elements.append(journal_table)

                if journal_entry.get("memo"):
                    elements.append(Spacer(1, 0.05 * inch))
                    elements.append(
                        Paragraph(
                            f"<i>Memo: {journal_entry.get('memo')}</i>",
                            normal_style,
                        )
                    )

            elements.append(Spacer(1, 0.3 * inch))

            # Add page break every 2-3 documents to avoid crowding
            if idx % 3 == 0 and idx < len(results):
                elements.append(PageBreak())

    # Footer note
    elements.append(Spacer(1, 0.5 * inch))
    elements.append(
        Paragraph(
            "<i>This report was generated by an AI-powered reconciliation system. "
            "All decisions should be reviewed by authorized personnel before finalization.</i>",
            ParagraphStyle(
                "Footer",
                parent=styles["Normal"],
                fontSize=8,
                textColor=colors.grey,
                alignment=TA_CENTER,
            ),
        )
    )

    # Build PDF
    doc.build(elements)

    # Get the value of the BytesIO buffer
    pdf_bytes = buffer.getvalue()
    buffer.close()

    return pdf_bytes
